// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jpcxmeympebywlxptgub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpwY3htZXltcGVieXdseHB0Z3ViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4OTQ5MDMsImV4cCI6MjA2NDQ3MDkwM30.CuYnvq_jgDdjPoh-qmVv8p92StV265U31kvJK9oi8l4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);